### PR TITLE
Introduce Motion Detection v1

### PR DESCRIPTION
**Pull request by toliuweijing**
**Description**
One typical use case is a baby monitor. This PR introduce the basic motion detection feature. It uses OpenCV to check  movements between two consecutive video frames. Once detected, a notification will be sent.

| Entry | Notification Group | Settings 
|-|-|-
|output|image|image
|The entry point is on the top-right button from the Display side. Clicking the button remotely enables the detection logic on the Camera side.|The notifications are grouped with the detection time in the subtitle.|User can change the sound for motion detection notification channel in the app notification settings.

**Test Plan**
- [x] Toggle entry point on/off. Verify the feature is configrured properly.
- [x] Test on SDK 33, verify the push notification shows up in the permission request list.
- [x] Test on pre-SDK 33, verify no permission needed for push notification.
- [x] Reduce false alarm by addressing the cooldown window and contour area size.
- [x] Test in night / low-light environment, verify motion detection works as expected.
- [x] Test in different distances,(e.g. bed room, out door), verify motion detection works as expected.

**V2 Plan / Backlog**
- [ ] Occasionally, a false alarm can be triggered by camera autofocusing without any movement on the scene, which changes the content of the video frame and trigger a detected notification. This can be resolved by using a fixed focus distance only for this feature. 
- [ ] Consider a night vision by manually increasing the brightness via exposure / ISO.
- [ ] Consider a setting page for users to fine tune the thresholds for their needs, e.g. cooldown duration, recovery time from detected to not_detected, etc.
- [ ] Play the notification sound by changing the audio output from earpiece to speaker. See [demo](https://github.com/toliuweijing/RemoteVideoCam/pull/12/files)

### CODE REVIEW

**Comment by toliuweijing** [comment]
@izivkov do you have suggestion of other test cases?

**Comment by izivkov** [comment]
No, I think that looks great. Let me play with the new code for a day or so, and if you are OK with it, we can merge the PR.

Ivo

**Comment by toliuweijing** [comment]
> No, I think that looks great. Let me play with the new code for a day or so, and if you are OK with it, we can merge the PR.
> 
> Ivo

Sounds good. Let me know if you encountered any issues. I will do more testings over the weekend. If no major issues found, we can merge in Monday and iterate on v2.

**Comment by toliuweijing** [comment]
@izivkov No major issues is found in the last two days. Could you share your test result? If good, please help merge the PR. (Need write access to the repo)

**Comment by izivkov** [comment]
I'll do some tests tonight and tomorrow. I've been quite busy in these
days. We should be able to merge by the end of the weekend.
Regards

**Comment by izivkov** [comment]
Jim, I started testing, and it looks really good. A couple of minor issues so far:

1. After detecting motion, the notification is displayed correctly. Now, if you exit monitor mode and enter again, and motion is detected, I think the notification should be shown again right away, without having to wait for the time between notifications.
3. The displayed time on the notification should be localized, like 9:30:00 PM for North America and 21:30:00 for elsewhere.
4. There are other issues, but I don't think they are related to this PR, so I will not address them here."

**Comment by toliuweijing** [comment]
Great feedback. I have followed up the fixes. Free feel to test on the latest commit.

> I've been quite busy in these
days. We should be able to merge by the end of the weekend.

Thanks for letting me know. The PR is not urgent at all. Feel free to take more time in testing.

> After detecting motion, the notification is displayed correctly. Now, if you exit monitor mode and enter again, and motion is detected, I think the notification should be shown again right away, without having to wait for the time between notifications.

Addresed at https://github.com/izivkov/RemoteVideoCam/pull/23/commits/98172530927be60e35fdaae4c6b6460ed75824c1

> The displayed time on the notification should be localized, like 9:30:00 PM for North America and 21:30:00 for elsewhere.

Addressed at https://github.com/izivkov/RemoteVideoCam/pull/23/commits/f1a31c34c4981619d798c2ad7d39df354491aec2

**Comment by izivkov** [comment]
Perfect, I will merge it and update the app on PlayStore and F-DROID. 

Thanks for your great work. If you are ready to tacle another issie, let me know.

**Comment by izivkov** [comment]
I updated both the PlayStore app anf the F-DROID. It takes about a week the see the new app v3.3 on F-DROID.

**Comment by toliuweijing** [comment]
Thank you for the quick turnaround. I will check the playstore feedback if usres run into any issue. 

> If you are ready to tacle another issie, let me know.

Sure. Let me know the next important issue. I also have some ideas to explore. Let me know where I can put down those(Discussion or Issue)?

**Comment by izivkov** [comment]
I like to hear your ideas. Please open in Dicussions.

The next feature I would like to add is another type of connection to allow the phones to talk point-to-point (without a WiFi router). I will add more info later.

**Pull request merged**
